CREATE SCHEMA $1 AUTHORIZATION adm_$1;
ALTER USER adm_$1 SET search_path = $1, public;
ALTER USER $1 WITH PASSWORD '$2';
GRANT CONNECT ON DATABASE dbtpv TO adm_$1;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA $1 TO adm_$1;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA $1 TO adm_$1;
