CREATE USER adm_paciente0 WITH LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
CREATE SCHEMA paciente0 AUTHORIZATION adm_paciente0;
ALTER USER adm_paciente0 SET search_path = paciente0, public;
ALTER USER adm_paciente0 WITH PASSWORD '12345678';
GRANT CONNECT ON DATABASE dbtpv TO adm_paciente0;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA paciente0 TO adm_paciente0;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA paciente0 TO adm_paciente0;
